# Generated by Django 3.1.7 on 2021-05-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_physician',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_specialist',
            field=models.BooleanField(),
        ),
    ]
