# Generated by Django 3.1.7 on 2021-06-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210530_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_physician',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_specialist',
        ),
        migrations.AddField(
            model_name='user',
            name='medicall_staffer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='specialist_area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
