# Generated by Django 3.1.7 on 2021-06-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='recommended_diagnosis',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
